### ISSUE TITLE
Research Payment API

### ISSUE THREAD

**Issue by jacesimons14** [NoahBays/Divisible#14]
We need to research which API (if either) is still up/easy to use/free, etc.
Research possible payment api's that we can use to implement Divisible's core functionality.
NOTE: this ticket is NOT to actually _implement_ the api, but rather to research and **decide** which api to use for said ticket.

**Comment by jogi9928** [comment]
Find payment API to use for easy financial transactions between users. Try to find API's for well-known payment forms such as PayPal or Venmo.

**Comment by jogi9928** [comment]
paypal is free and easy to use!
